version: "3"
services:

  app:
    build:
      context: ./wb370
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: wb370database
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

